theophilusx/ssh2-sftp-client

src/index.js
The current implementation does not use properly the Promises for the 'SftpClient.rmdir' method if the flag 'recursive' is set to 'true', as a result the 'sftp.rmdir' is called after the outer Promise is resolved.
With this fix the outer Promise will be either resolved or rejected only after the 'sftp.rmdir' is finished.
=> Fix for recursive version of rmdir

src/index.js
In both `get` and `put` we can trigger an error before an error event handler can be attached in user's `resolve` handler. A good example being trying to get a non existent file.
=> Error events can fire before the stream is resolved

README.md, src/index.js, test/index.js
Support for stream encodings. The previous implementation forced 'utf8' which did not work well with binary data. New implementation allows to pass optional parameter 'encoding' to get() and put() methods. If 'encoding' is undefined, it will default to 'utf8'.
The change is backwards compatible.
=> Support for stream encoding

src/index.js
Most sftp servers use error code 4 'Failure' for everything but some use a wider range of errors.  See here: https://winscp.net/eng/docs/sftp_codes
Error code 11 means 'File already exists' and should be ignored when recursively creating directories.
=> Ignore error code 11 'File already exists' when recursively creating directories

package.json, src/index.js, src/utils.js
This maintains support with older versions of NodeJS, as some linux distributions (CentOS) still have older versions of NodeJS which don't support async/await syntax.
Btw, I did not test these methods very much, but I trust the person who wrote the tests, as it still passes them 100%.
=> Changed async/await methods to Promises

src/index.js
Remote directory separator must be "/", like posix (see https://tools.ietf.org/html/draft-ietf-secsh-filexfer-13#section-6)
Then use `require('path').posix` instead of `require('path')`
=> use posix path

README.md
The readme had the old v3 description for `get`
=> Fix `get` in README

src/index.js
This change causes SFTPClient.prototype.connect to reject the returned promise if the underlying SSH client closes in the meantime, before the SFTP subsystem is ready.
In some cases (notably, upon getting a TCP RST), the client would emit an `end` event and become inactive, ignoring further requests. However, since no `error` was being emitted from the client object, connect() would not fail, instead hanging indefinitely.
For jyu213/ssh2-sftp-client#109
=> Reject connect() promise if connection ends

package.json
Version `0.8.2` of the `ssh2` package includes updates from the `ssh2-stream` dependency for parsing private keys.  Additional private key formats (including the "new" OpenSSH key format) are now supported with this version bump.
After upgrading the `ssh2` package, the existing unit tests pass.
=> Update ssh2 dependency to 0.8.2

README.md
To avoid a "failed to upload" error, you have to put the target file name as well as the path.
=> Update README.md to call out put() requirement

package.json, src/index.js
Adding Retry functionality to connect
Pass extra key to config:
config = {
host: "",
....,
retries: 1 //Seting this to 1 means do it once, then retry it 1 times, i.e. (retries + 1) 2 times
}
=> Adding retry to connect

package.json, src/index.js
I ran into an infinite loop when trying to use recursive mkdir without proper permissions. I did some tests and found if I add this base-case it behaves as expected, throwing a "Permission denied" error.
=> Add a base case to mkdir recursive, prevent infinite looping

README.md, README.org
Buffers are not supported by this method, only strings and write streams.
I tried using a `Buffer`, much to my disappointment :(
=> Remove `Buffer` as a valid destination parameter

README.md, README.org
Various fixes to `README.md` and `README.org`:
- Fixed several typos
- Corrected capitalization and punctuation
- Removed extraneous whitespace
Note: due to the whitespace changes, it's easier to view the diff of each commit separately, or alternatively view the [full PR diff in whitespace-insensitive mode](https://github.com/theophilusx/ssh2-sftp-client/pull/178/files?w=1).
=> Fix several typos in README.md and README.org

README.org
- Various whitespace fixes
- Harmonize indentation in Changelog section
- change syntax highlighting from `js2` to `javascript` (as discussed [here](https://github.com/theophilusx/ssh2-sftp-client/commit/7b92d67ae#commitcomment-35662731))
- Change markdown syntax to the correct org-mode syntax
=> Various improvements to README.org

README.md, README.org
Fixes a small readme typo. sftp.gastGet() -> sftp.fastGet()
=> docs: Fix a readme typo

src/index.js
If a user calls the `put` method with options that include `readStreamOptions` _and_ the `localSrc` is a string, the `readStreamOptions` options are not currently being used due to a typo.
-  fixes typo
=> [bug fix] Corrects typo in `put` method to ensure options args are used if set (when `localSrc` string)

src/index.js, test/01connections.js
Fixes #353, a regression from 7.0.1, and adds a test to verify this for future versions.
=> Fix connect() not returning the sftp channel

src/index.js
This fixes the issue #355 by resolving the promise after the write stream emits `close` instead of `finish`.
=> fix: Resolve PUT method on Writable 'close' instead of 'finish'

test/19utils.js
...... because we created a symbolic file before
=> unlink, not rm

src/index.js, src/utils.js
temp listeners will re decoupled after each operation from the same client. Fixes #362
=> fix:moved temp listeners to the scope of client.

src/utils.js
Clearing the `obj.tempListeners` and setting it from an `object` to an `array` gives me the following error when trying to read a file to a write stream using the 'get' command:
```
TypeError: obj.tempListeners[name].forEach is not a function
at removeTempListeners (/home/new/node_modules/ssh2-sftp-client/src/utils.js:148:29)
at /home/new/node_modules/ssh2-sftp-client/src/index.js:545:7
at <anonymous>
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
I think you ment to clear the array of events of a key in the 'tempListeners' object, not the entire object itself. This small change fixes the error for me and allowed me to succesfully download the file from the SFTP server.
=> Updated removeTempListeners to clear the specific tempListeners array

src/index.js
Hi. Thanks for your work!
I found that with downloadDir filter and useFastGET options isn't propagated to recursive calls.
=> recursive filter in downloadDir

README.org
When destructuring the return object from SocksClient.createConnection(), socket should be used.
=> socks connection documentation update

README.org
Explicitly describe that `downloadDir` will download the **content** of `srcDir`, and not `srcDir` itself.
https://github.com/theophilusx/ssh2-sftp-client/blob/v10.0.3/src/index.js#L1383
IIUC, `README.md` is generated from `README.org`, so I modified the latter only. https://github.com/theophilusx/ssh2-sftp-client?tab=readme-ov-file#pull-requests
=> docs(README.org): downloadDir explicit work on content
